/**
 * QuantiModo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PostCorrelation {
  
  @SerializedName("causeVariableName")
  private String causeVariableName = null;
  @SerializedName("effectVariableName")
  private String effectVariableName = null;
  @SerializedName("correlation")
  private Double correlation = null;
  @SerializedName("vote")
  private Integer vote = null;

  /**
   * Cause variable name
   **/
  @ApiModelProperty(required = true, value = "Cause variable name")
  public String getCauseVariableName() {
    return causeVariableName;
  }
  public void setCauseVariableName(String causeVariableName) {
    this.causeVariableName = causeVariableName;
  }

  /**
   * Effect variable name
   **/
  @ApiModelProperty(required = true, value = "Effect variable name")
  public String getEffectVariableName() {
    return effectVariableName;
  }
  public void setEffectVariableName(String effectVariableName) {
    this.effectVariableName = effectVariableName;
  }

  /**
   * Correlation value
   **/
  @ApiModelProperty(required = true, value = "Correlation value")
  public Double getCorrelation() {
    return correlation;
  }
  public void setCorrelation(Double correlation) {
    this.correlation = correlation;
  }

  /**
   * Vote: 0 or 1
   **/
  @ApiModelProperty(value = "Vote: 0 or 1")
  public Integer getVote() {
    return vote;
  }
  public void setVote(Integer vote) {
    this.vote = vote;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostCorrelation postCorrelation = (PostCorrelation) o;
    return (this.causeVariableName == null ? postCorrelation.causeVariableName == null : this.causeVariableName.equals(postCorrelation.causeVariableName)) &&
        (this.effectVariableName == null ? postCorrelation.effectVariableName == null : this.effectVariableName.equals(postCorrelation.effectVariableName)) &&
        (this.correlation == null ? postCorrelation.correlation == null : this.correlation.equals(postCorrelation.correlation)) &&
        (this.vote == null ? postCorrelation.vote == null : this.vote.equals(postCorrelation.vote));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.causeVariableName == null ? 0: this.causeVariableName.hashCode());
    result = 31 * result + (this.effectVariableName == null ? 0: this.effectVariableName.hashCode());
    result = 31 * result + (this.correlation == null ? 0: this.correlation.hashCode());
    result = 31 * result + (this.vote == null ? 0: this.vote.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostCorrelation {\n");
    
    sb.append("  causeVariableName: ").append(causeVariableName).append("\n");
    sb.append("  effectVariableName: ").append(effectVariableName).append("\n");
    sb.append("  correlation: ").append(correlation).append("\n");
    sb.append("  vote: ").append(vote).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
