/**
 * QuantiModo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UserVariable {
  
  @SerializedName("parentId")
  private Integer parentId = null;
  @SerializedName("userId")
  private Integer userId = null;
  @SerializedName("clientId")
  private String clientId = null;
  @SerializedName("variableId")
  private Integer variableId = null;
  @SerializedName("defaultUnitId")
  private Integer defaultUnitId = null;
  @SerializedName("minimumAllowedValue")
  private Float minimumAllowedValue = null;
  @SerializedName("maximumAllowedValue")
  private Float maximumAllowedValue = null;
  @SerializedName("fillingValue")
  private Float fillingValue = null;
  @SerializedName("joinWith")
  private Integer joinWith = null;
  @SerializedName("onsetDelay")
  private Integer onsetDelay = null;
  @SerializedName("durationOfAction")
  private Integer durationOfAction = null;
  @SerializedName("variableCategoryId")
  private Integer variableCategoryId = null;
  @SerializedName("updated")
  private Integer updated = null;
  @SerializedName("public")
  private Integer _public = null;
  @SerializedName("causeOnly")
  private Boolean causeOnly = null;
  @SerializedName("fillingType")
  private String fillingType = null;
  @SerializedName("numberOfMeasurements")
  private Integer numberOfMeasurements = null;
  @SerializedName("numberOfProcessedDailyMeasurements")
  private Integer numberOfProcessedDailyMeasurements = null;
  @SerializedName("measurementsAtLastAnalysis")
  private Integer measurementsAtLastAnalysis = null;
  @SerializedName("lastUnitId")
  private Integer lastUnitId = null;
  @SerializedName("lastOriginalUnitId")
  private Integer lastOriginalUnitId = null;
  @SerializedName("lastValue")
  private Float lastValue = null;
  @SerializedName("lastOriginalValue")
  private Integer lastOriginalValue = null;
  @SerializedName("numberOfCorrelations")
  private Integer numberOfCorrelations = null;
  @SerializedName("status")
  private String status = null;
  @SerializedName("errorMessage")
  private String errorMessage = null;
  @SerializedName("lastSuccessfulUpdateTime")
  private Date lastSuccessfulUpdateTime = null;
  @SerializedName("standard_deviation")
  private Float standardDeviation = null;
  @SerializedName("variance")
  private Float variance = null;
  @SerializedName("minimumRecordedValue")
  private Float minimumRecordedValue = null;
  @SerializedName("maximumRecordedDailyValue")
  private Float maximumRecordedDailyValue = null;
  @SerializedName("mean")
  private Float mean = null;
  @SerializedName("median")
  private Float median = null;
  @SerializedName("mostCommonUnitId")
  private Integer mostCommonUnitId = null;
  @SerializedName("mostCommonValue")
  private Float mostCommonValue = null;
  @SerializedName("numberOfUniqueDailyValues")
  private Float numberOfUniqueDailyValues = null;
  @SerializedName("numberOfChanges")
  private Integer numberOfChanges = null;
  @SerializedName("skewness")
  private Float skewness = null;
  @SerializedName("kurtosis")
  private Float kurtosis = null;
  @SerializedName("latitude")
  private Float latitude = null;
  @SerializedName("longitude")
  private Float longitude = null;
  @SerializedName("location")
  private String location = null;
  @SerializedName("experimentStartTime")
  private Date experimentStartTime = null;
  @SerializedName("experimentEndTime")
  private Date experimentEndTime = null;
  @SerializedName("createdAt")
  private Date createdAt = null;
  @SerializedName("updatedAt")
  private Date updatedAt = null;
  @SerializedName("outcome")
  private Boolean outcome = null;
  @SerializedName("sources")
  private String sources = null;
  @SerializedName("earliestSourceTime")
  private Integer earliestSourceTime = null;
  @SerializedName("latestSourceTime")
  private Integer latestSourceTime = null;
  @SerializedName("earliestMeasurementTime")
  private Integer earliestMeasurementTime = null;
  @SerializedName("latestMeasurementTime")
  private Integer latestMeasurementTime = null;
  @SerializedName("earliestFillingTime")
  private Integer earliestFillingTime = null;
  @SerializedName("latestFillingTime")
  private Integer latestFillingTime = null;
  @SerializedName("imageUrl")
  private String imageUrl = null;
  @SerializedName("ionIcon")
  private String ionIcon = null;

  /**
   * ID of the parent variable if this variable has any parent
   **/
  @ApiModelProperty(value = "ID of the parent variable if this variable has any parent")
  public Integer getParentId() {
    return parentId;
  }
  public void setParentId(Integer parentId) {
    this.parentId = parentId;
  }

  /**
   * User ID
   **/
  @ApiModelProperty(value = "User ID")
  public Integer getUserId() {
    return userId;
  }
  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  /**
   * clientId
   **/
  @ApiModelProperty(value = "clientId")
  public String getClientId() {
    return clientId;
  }
  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  /**
   * ID of variable
   **/
  @ApiModelProperty(required = true, value = "ID of variable")
  public Integer getVariableId() {
    return variableId;
  }
  public void setVariableId(Integer variableId) {
    this.variableId = variableId;
  }

  /**
   * ID of unit to use for this variable
   **/
  @ApiModelProperty(value = "ID of unit to use for this variable")
  public Integer getDefaultUnitId() {
    return defaultUnitId;
  }
  public void setDefaultUnitId(Integer defaultUnitId) {
    this.defaultUnitId = defaultUnitId;
  }

  /**
   * The minimum allowed value for measurements. While you can record a value below this minimum, it will be excluded from the correlation analysis.
   **/
  @ApiModelProperty(value = "The minimum allowed value for measurements. While you can record a value below this minimum, it will be excluded from the correlation analysis.")
  public Float getMinimumAllowedValue() {
    return minimumAllowedValue;
  }
  public void setMinimumAllowedValue(Float minimumAllowedValue) {
    this.minimumAllowedValue = minimumAllowedValue;
  }

  /**
   * The maximum allowed value for measurements. While you can record a value above this maximum, it will be excluded from the correlation analysis.
   **/
  @ApiModelProperty(value = "The maximum allowed value for measurements. While you can record a value above this maximum, it will be excluded from the correlation analysis.")
  public Float getMaximumAllowedValue() {
    return maximumAllowedValue;
  }
  public void setMaximumAllowedValue(Float maximumAllowedValue) {
    this.maximumAllowedValue = maximumAllowedValue;
  }

  /**
   * When it comes to analysis to determine the effects of this variable, knowing when it did not occur is as important as knowing when it did occur. For example, if you are tracking a medication, it is important to know when you did not take it, but you do not have to log zero values for all the days when you haven't taken it. Hence, you can specify a filling value (typically 0) to insert whenever data is missing.
   **/
  @ApiModelProperty(value = "When it comes to analysis to determine the effects of this variable, knowing when it did not occur is as important as knowing when it did occur. For example, if you are tracking a medication, it is important to know when you did not take it, but you do not have to log zero values for all the days when you haven't taken it. Hence, you can specify a filling value (typically 0) to insert whenever data is missing.")
  public Float getFillingValue() {
    return fillingValue;
  }
  public void setFillingValue(Float fillingValue) {
    this.fillingValue = fillingValue;
  }

  /**
   * The Variable this Variable should be joined with. If the variable is joined with some other variable then it is not shown to user in the list of variables
   **/
  @ApiModelProperty(value = "The Variable this Variable should be joined with. If the variable is joined with some other variable then it is not shown to user in the list of variables")
  public Integer getJoinWith() {
    return joinWith;
  }
  public void setJoinWith(Integer joinWith) {
    this.joinWith = joinWith;
  }

  /**
   * The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes.
   **/
  @ApiModelProperty(value = "The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes.")
  public Integer getOnsetDelay() {
    return onsetDelay;
  }
  public void setOnsetDelay(Integer onsetDelay) {
    this.onsetDelay = onsetDelay;
  }

  /**
   * The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.
   **/
  @ApiModelProperty(value = "The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.")
  public Integer getDurationOfAction() {
    return durationOfAction;
  }
  public void setDurationOfAction(Integer durationOfAction) {
    this.durationOfAction = durationOfAction;
  }

  /**
   * ID of variable category
   **/
  @ApiModelProperty(value = "ID of variable category")
  public Integer getVariableCategoryId() {
    return variableCategoryId;
  }
  public void setVariableCategoryId(Integer variableCategoryId) {
    this.variableCategoryId = variableCategoryId;
  }

  /**
   * updated
   **/
  @ApiModelProperty(value = "updated")
  public Integer getUpdated() {
    return updated;
  }
  public void setUpdated(Integer updated) {
    this.updated = updated;
  }

  /**
   * Is variable public
   **/
  @ApiModelProperty(value = "Is variable public")
  public Integer getPublic() {
    return _public;
  }
  public void setPublic(Integer _public) {
    this._public = _public;
  }

  /**
   * A value of 1 indicates that this variable is generally a cause in a causal relationship.  An example of a causeOnly variable would be a variable such as Cloud Cover which would generally not be influenced by the behaviour of the user
   **/
  @ApiModelProperty(value = "A value of 1 indicates that this variable is generally a cause in a causal relationship.  An example of a causeOnly variable would be a variable such as Cloud Cover which would generally not be influenced by the behaviour of the user")
  public Boolean getCauseOnly() {
    return causeOnly;
  }
  public void setCauseOnly(Boolean causeOnly) {
    this.causeOnly = causeOnly;
  }

  /**
   * 0 -> No filling, 1 -> Use filling-value
   **/
  @ApiModelProperty(value = "0 -> No filling, 1 -> Use filling-value")
  public String getFillingType() {
    return fillingType;
  }
  public void setFillingType(String fillingType) {
    this.fillingType = fillingType;
  }

  /**
   * Number of measurements
   **/
  @ApiModelProperty(value = "Number of measurements")
  public Integer getNumberOfMeasurements() {
    return numberOfMeasurements;
  }
  public void setNumberOfMeasurements(Integer numberOfMeasurements) {
    this.numberOfMeasurements = numberOfMeasurements;
  }

  /**
   * Number of processed measurements
   **/
  @ApiModelProperty(value = "Number of processed measurements")
  public Integer getNumberOfProcessedDailyMeasurements() {
    return numberOfProcessedDailyMeasurements;
  }
  public void setNumberOfProcessedDailyMeasurements(Integer numberOfProcessedDailyMeasurements) {
    this.numberOfProcessedDailyMeasurements = numberOfProcessedDailyMeasurements;
  }

  /**
   * Number of measurements at last analysis
   **/
  @ApiModelProperty(value = "Number of measurements at last analysis")
  public Integer getMeasurementsAtLastAnalysis() {
    return measurementsAtLastAnalysis;
  }
  public void setMeasurementsAtLastAnalysis(Integer measurementsAtLastAnalysis) {
    this.measurementsAtLastAnalysis = measurementsAtLastAnalysis;
  }

  /**
   * ID of last Unit
   **/
  @ApiModelProperty(value = "ID of last Unit")
  public Integer getLastUnitId() {
    return lastUnitId;
  }
  public void setLastUnitId(Integer lastUnitId) {
    this.lastUnitId = lastUnitId;
  }

  /**
   * ID of last original Unit
   **/
  @ApiModelProperty(value = "ID of last original Unit")
  public Integer getLastOriginalUnitId() {
    return lastOriginalUnitId;
  }
  public void setLastOriginalUnitId(Integer lastOriginalUnitId) {
    this.lastOriginalUnitId = lastOriginalUnitId;
  }

  /**
   * Last Value
   **/
  @ApiModelProperty(value = "Last Value")
  public Float getLastValue() {
    return lastValue;
  }
  public void setLastValue(Float lastValue) {
    this.lastValue = lastValue;
  }

  /**
   * Last original value which is stored
   **/
  @ApiModelProperty(value = "Last original value which is stored")
  public Integer getLastOriginalValue() {
    return lastOriginalValue;
  }
  public void setLastOriginalValue(Integer lastOriginalValue) {
    this.lastOriginalValue = lastOriginalValue;
  }

  /**
   * Number of correlations for this variable
   **/
  @ApiModelProperty(value = "Number of correlations for this variable")
  public Integer getNumberOfCorrelations() {
    return numberOfCorrelations;
  }
  public void setNumberOfCorrelations(Integer numberOfCorrelations) {
    this.numberOfCorrelations = numberOfCorrelations;
  }

  /**
   * status
   **/
  @ApiModelProperty(value = "status")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   * error_message
   **/
  @ApiModelProperty(value = "error_message")
  public String getErrorMessage() {
    return errorMessage;
  }
  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  /**
   * When this variable or its settings were last updated
   **/
  @ApiModelProperty(value = "When this variable or its settings were last updated")
  public Date getLastSuccessfulUpdateTime() {
    return lastSuccessfulUpdateTime;
  }
  public void setLastSuccessfulUpdateTime(Date lastSuccessfulUpdateTime) {
    this.lastSuccessfulUpdateTime = lastSuccessfulUpdateTime;
  }

  /**
   * Standard deviation
   **/
  @ApiModelProperty(value = "Standard deviation")
  public Float getStandardDeviation() {
    return standardDeviation;
  }
  public void setStandardDeviation(Float standardDeviation) {
    this.standardDeviation = standardDeviation;
  }

  /**
   * Variance
   **/
  @ApiModelProperty(value = "Variance")
  public Float getVariance() {
    return variance;
  }
  public void setVariance(Float variance) {
    this.variance = variance;
  }

  /**
   * Minimum recorded value of this variable
   **/
  @ApiModelProperty(value = "Minimum recorded value of this variable")
  public Float getMinimumRecordedValue() {
    return minimumRecordedValue;
  }
  public void setMinimumRecordedValue(Float minimumRecordedValue) {
    this.minimumRecordedValue = minimumRecordedValue;
  }

  /**
   * Maximum recorded daily value of this variable
   **/
  @ApiModelProperty(value = "Maximum recorded daily value of this variable")
  public Float getMaximumRecordedDailyValue() {
    return maximumRecordedDailyValue;
  }
  public void setMaximumRecordedDailyValue(Float maximumRecordedDailyValue) {
    this.maximumRecordedDailyValue = maximumRecordedDailyValue;
  }

  /**
   * Mean
   **/
  @ApiModelProperty(value = "Mean")
  public Float getMean() {
    return mean;
  }
  public void setMean(Float mean) {
    this.mean = mean;
  }

  /**
   * Median
   **/
  @ApiModelProperty(value = "Median")
  public Float getMedian() {
    return median;
  }
  public void setMedian(Float median) {
    this.median = median;
  }

  /**
   * Most common Unit ID
   **/
  @ApiModelProperty(value = "Most common Unit ID")
  public Integer getMostCommonUnitId() {
    return mostCommonUnitId;
  }
  public void setMostCommonUnitId(Integer mostCommonUnitId) {
    this.mostCommonUnitId = mostCommonUnitId;
  }

  /**
   * Most common value
   **/
  @ApiModelProperty(value = "Most common value")
  public Float getMostCommonValue() {
    return mostCommonValue;
  }
  public void setMostCommonValue(Float mostCommonValue) {
    this.mostCommonValue = mostCommonValue;
  }

  /**
   * Number of unique daily values
   **/
  @ApiModelProperty(value = "Number of unique daily values")
  public Float getNumberOfUniqueDailyValues() {
    return numberOfUniqueDailyValues;
  }
  public void setNumberOfUniqueDailyValues(Float numberOfUniqueDailyValues) {
    this.numberOfUniqueDailyValues = numberOfUniqueDailyValues;
  }

  /**
   * Number of changes
   **/
  @ApiModelProperty(value = "Number of changes")
  public Integer getNumberOfChanges() {
    return numberOfChanges;
  }
  public void setNumberOfChanges(Integer numberOfChanges) {
    this.numberOfChanges = numberOfChanges;
  }

  /**
   * Skewness
   **/
  @ApiModelProperty(value = "Skewness")
  public Float getSkewness() {
    return skewness;
  }
  public void setSkewness(Float skewness) {
    this.skewness = skewness;
  }

  /**
   * Kurtosis
   **/
  @ApiModelProperty(value = "Kurtosis")
  public Float getKurtosis() {
    return kurtosis;
  }
  public void setKurtosis(Float kurtosis) {
    this.kurtosis = kurtosis;
  }

  /**
   * Latitude
   **/
  @ApiModelProperty(value = "Latitude")
  public Float getLatitude() {
    return latitude;
  }
  public void setLatitude(Float latitude) {
    this.latitude = latitude;
  }

  /**
   * Longitude
   **/
  @ApiModelProperty(value = "Longitude")
  public Float getLongitude() {
    return longitude;
  }
  public void setLongitude(Float longitude) {
    this.longitude = longitude;
  }

  /**
   * Location
   **/
  @ApiModelProperty(value = "Location")
  public String getLocation() {
    return location;
  }
  public void setLocation(String location) {
    this.location = location;
  }

  /**
   * Earliest measurement start_time to be used in analysis. Use UTC ISO 8601 \"YYYY-MM-DDThh:mm:ss\"  datetime format
   **/
  @ApiModelProperty(value = "Earliest measurement start_time to be used in analysis. Use UTC ISO 8601 \"YYYY-MM-DDThh:mm:ss\"  datetime format")
  public Date getExperimentStartTime() {
    return experimentStartTime;
  }
  public void setExperimentStartTime(Date experimentStartTime) {
    this.experimentStartTime = experimentStartTime;
  }

  /**
   * Latest measurement start_time to be used in analysis. Use UTC ISO 8601 \"YYYY-MM-DDThh:mm:ss\"  datetime format
   **/
  @ApiModelProperty(value = "Latest measurement start_time to be used in analysis. Use UTC ISO 8601 \"YYYY-MM-DDThh:mm:ss\"  datetime format")
  public Date getExperimentEndTime() {
    return experimentEndTime;
  }
  public void setExperimentEndTime(Date experimentEndTime) {
    this.experimentEndTime = experimentEndTime;
  }

  /**
   * When the record was first created. Use UTC ISO 8601 \"YYYY-MM-DDThh:mm:ss\"  datetime format
   **/
  @ApiModelProperty(value = "When the record was first created. Use UTC ISO 8601 \"YYYY-MM-DDThh:mm:ss\"  datetime format")
  public Date getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }

  /**
   * When the record in the database was last updated. Use UTC ISO 8601 \"YYYY-MM-DDThh:mm:ss\"  datetime format
   **/
  @ApiModelProperty(value = "When the record in the database was last updated. Use UTC ISO 8601 \"YYYY-MM-DDThh:mm:ss\"  datetime format")
  public Date getUpdatedAt() {
    return updatedAt;
  }
  public void setUpdatedAt(Date updatedAt) {
    this.updatedAt = updatedAt;
  }

  /**
   * Outcome variables (those with `outcome` == 1) are variables for which a human would generally want to identify the influencing factors. These include symptoms of illness, physique, mood, cognitive performance, etc.  Generally correlation calculations are only performed on outcome variables
   **/
  @ApiModelProperty(value = "Outcome variables (those with `outcome` == 1) are variables for which a human would generally want to identify the influencing factors. These include symptoms of illness, physique, mood, cognitive performance, etc.  Generally correlation calculations are only performed on outcome variables")
  public Boolean getOutcome() {
    return outcome;
  }
  public void setOutcome(Boolean outcome) {
    this.outcome = outcome;
  }

  /**
   * Comma-separated list of source names to limit variables to those sources
   **/
  @ApiModelProperty(value = "Comma-separated list of source names to limit variables to those sources")
  public String getSources() {
    return sources;
  }
  public void setSources(String sources) {
    this.sources = sources;
  }

  /**
   * Earliest source time
   **/
  @ApiModelProperty(value = "Earliest source time")
  public Integer getEarliestSourceTime() {
    return earliestSourceTime;
  }
  public void setEarliestSourceTime(Integer earliestSourceTime) {
    this.earliestSourceTime = earliestSourceTime;
  }

  /**
   * Latest source time
   **/
  @ApiModelProperty(value = "Latest source time")
  public Integer getLatestSourceTime() {
    return latestSourceTime;
  }
  public void setLatestSourceTime(Integer latestSourceTime) {
    this.latestSourceTime = latestSourceTime;
  }

  /**
   * Earliest measurement time
   **/
  @ApiModelProperty(value = "Earliest measurement time")
  public Integer getEarliestMeasurementTime() {
    return earliestMeasurementTime;
  }
  public void setEarliestMeasurementTime(Integer earliestMeasurementTime) {
    this.earliestMeasurementTime = earliestMeasurementTime;
  }

  /**
   * Latest measurement time
   **/
  @ApiModelProperty(value = "Latest measurement time")
  public Integer getLatestMeasurementTime() {
    return latestMeasurementTime;
  }
  public void setLatestMeasurementTime(Integer latestMeasurementTime) {
    this.latestMeasurementTime = latestMeasurementTime;
  }

  /**
   * Earliest filling time
   **/
  @ApiModelProperty(value = "Earliest filling time")
  public Integer getEarliestFillingTime() {
    return earliestFillingTime;
  }
  public void setEarliestFillingTime(Integer earliestFillingTime) {
    this.earliestFillingTime = earliestFillingTime;
  }

  /**
   * Latest filling time
   **/
  @ApiModelProperty(value = "Latest filling time")
  public Integer getLatestFillingTime() {
    return latestFillingTime;
  }
  public void setLatestFillingTime(Integer latestFillingTime) {
    this.latestFillingTime = latestFillingTime;
  }

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public String getImageUrl() {
    return imageUrl;
  }
  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public String getIonIcon() {
    return ionIcon;
  }
  public void setIonIcon(String ionIcon) {
    this.ionIcon = ionIcon;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserVariable userVariable = (UserVariable) o;
    return (this.parentId == null ? userVariable.parentId == null : this.parentId.equals(userVariable.parentId)) &&
        (this.userId == null ? userVariable.userId == null : this.userId.equals(userVariable.userId)) &&
        (this.clientId == null ? userVariable.clientId == null : this.clientId.equals(userVariable.clientId)) &&
        (this.variableId == null ? userVariable.variableId == null : this.variableId.equals(userVariable.variableId)) &&
        (this.defaultUnitId == null ? userVariable.defaultUnitId == null : this.defaultUnitId.equals(userVariable.defaultUnitId)) &&
        (this.minimumAllowedValue == null ? userVariable.minimumAllowedValue == null : this.minimumAllowedValue.equals(userVariable.minimumAllowedValue)) &&
        (this.maximumAllowedValue == null ? userVariable.maximumAllowedValue == null : this.maximumAllowedValue.equals(userVariable.maximumAllowedValue)) &&
        (this.fillingValue == null ? userVariable.fillingValue == null : this.fillingValue.equals(userVariable.fillingValue)) &&
        (this.joinWith == null ? userVariable.joinWith == null : this.joinWith.equals(userVariable.joinWith)) &&
        (this.onsetDelay == null ? userVariable.onsetDelay == null : this.onsetDelay.equals(userVariable.onsetDelay)) &&
        (this.durationOfAction == null ? userVariable.durationOfAction == null : this.durationOfAction.equals(userVariable.durationOfAction)) &&
        (this.variableCategoryId == null ? userVariable.variableCategoryId == null : this.variableCategoryId.equals(userVariable.variableCategoryId)) &&
        (this.updated == null ? userVariable.updated == null : this.updated.equals(userVariable.updated)) &&
        (this._public == null ? userVariable._public == null : this._public.equals(userVariable._public)) &&
        (this.causeOnly == null ? userVariable.causeOnly == null : this.causeOnly.equals(userVariable.causeOnly)) &&
        (this.fillingType == null ? userVariable.fillingType == null : this.fillingType.equals(userVariable.fillingType)) &&
        (this.numberOfMeasurements == null ? userVariable.numberOfMeasurements == null : this.numberOfMeasurements.equals(userVariable.numberOfMeasurements)) &&
        (this.numberOfProcessedDailyMeasurements == null ? userVariable.numberOfProcessedDailyMeasurements == null : this.numberOfProcessedDailyMeasurements.equals(userVariable.numberOfProcessedDailyMeasurements)) &&
        (this.measurementsAtLastAnalysis == null ? userVariable.measurementsAtLastAnalysis == null : this.measurementsAtLastAnalysis.equals(userVariable.measurementsAtLastAnalysis)) &&
        (this.lastUnitId == null ? userVariable.lastUnitId == null : this.lastUnitId.equals(userVariable.lastUnitId)) &&
        (this.lastOriginalUnitId == null ? userVariable.lastOriginalUnitId == null : this.lastOriginalUnitId.equals(userVariable.lastOriginalUnitId)) &&
        (this.lastValue == null ? userVariable.lastValue == null : this.lastValue.equals(userVariable.lastValue)) &&
        (this.lastOriginalValue == null ? userVariable.lastOriginalValue == null : this.lastOriginalValue.equals(userVariable.lastOriginalValue)) &&
        (this.numberOfCorrelations == null ? userVariable.numberOfCorrelations == null : this.numberOfCorrelations.equals(userVariable.numberOfCorrelations)) &&
        (this.status == null ? userVariable.status == null : this.status.equals(userVariable.status)) &&
        (this.errorMessage == null ? userVariable.errorMessage == null : this.errorMessage.equals(userVariable.errorMessage)) &&
        (this.lastSuccessfulUpdateTime == null ? userVariable.lastSuccessfulUpdateTime == null : this.lastSuccessfulUpdateTime.equals(userVariable.lastSuccessfulUpdateTime)) &&
        (this.standardDeviation == null ? userVariable.standardDeviation == null : this.standardDeviation.equals(userVariable.standardDeviation)) &&
        (this.variance == null ? userVariable.variance == null : this.variance.equals(userVariable.variance)) &&
        (this.minimumRecordedValue == null ? userVariable.minimumRecordedValue == null : this.minimumRecordedValue.equals(userVariable.minimumRecordedValue)) &&
        (this.maximumRecordedDailyValue == null ? userVariable.maximumRecordedDailyValue == null : this.maximumRecordedDailyValue.equals(userVariable.maximumRecordedDailyValue)) &&
        (this.mean == null ? userVariable.mean == null : this.mean.equals(userVariable.mean)) &&
        (this.median == null ? userVariable.median == null : this.median.equals(userVariable.median)) &&
        (this.mostCommonUnitId == null ? userVariable.mostCommonUnitId == null : this.mostCommonUnitId.equals(userVariable.mostCommonUnitId)) &&
        (this.mostCommonValue == null ? userVariable.mostCommonValue == null : this.mostCommonValue.equals(userVariable.mostCommonValue)) &&
        (this.numberOfUniqueDailyValues == null ? userVariable.numberOfUniqueDailyValues == null : this.numberOfUniqueDailyValues.equals(userVariable.numberOfUniqueDailyValues)) &&
        (this.numberOfChanges == null ? userVariable.numberOfChanges == null : this.numberOfChanges.equals(userVariable.numberOfChanges)) &&
        (this.skewness == null ? userVariable.skewness == null : this.skewness.equals(userVariable.skewness)) &&
        (this.kurtosis == null ? userVariable.kurtosis == null : this.kurtosis.equals(userVariable.kurtosis)) &&
        (this.latitude == null ? userVariable.latitude == null : this.latitude.equals(userVariable.latitude)) &&
        (this.longitude == null ? userVariable.longitude == null : this.longitude.equals(userVariable.longitude)) &&
        (this.location == null ? userVariable.location == null : this.location.equals(userVariable.location)) &&
        (this.experimentStartTime == null ? userVariable.experimentStartTime == null : this.experimentStartTime.equals(userVariable.experimentStartTime)) &&
        (this.experimentEndTime == null ? userVariable.experimentEndTime == null : this.experimentEndTime.equals(userVariable.experimentEndTime)) &&
        (this.createdAt == null ? userVariable.createdAt == null : this.createdAt.equals(userVariable.createdAt)) &&
        (this.updatedAt == null ? userVariable.updatedAt == null : this.updatedAt.equals(userVariable.updatedAt)) &&
        (this.outcome == null ? userVariable.outcome == null : this.outcome.equals(userVariable.outcome)) &&
        (this.sources == null ? userVariable.sources == null : this.sources.equals(userVariable.sources)) &&
        (this.earliestSourceTime == null ? userVariable.earliestSourceTime == null : this.earliestSourceTime.equals(userVariable.earliestSourceTime)) &&
        (this.latestSourceTime == null ? userVariable.latestSourceTime == null : this.latestSourceTime.equals(userVariable.latestSourceTime)) &&
        (this.earliestMeasurementTime == null ? userVariable.earliestMeasurementTime == null : this.earliestMeasurementTime.equals(userVariable.earliestMeasurementTime)) &&
        (this.latestMeasurementTime == null ? userVariable.latestMeasurementTime == null : this.latestMeasurementTime.equals(userVariable.latestMeasurementTime)) &&
        (this.earliestFillingTime == null ? userVariable.earliestFillingTime == null : this.earliestFillingTime.equals(userVariable.earliestFillingTime)) &&
        (this.latestFillingTime == null ? userVariable.latestFillingTime == null : this.latestFillingTime.equals(userVariable.latestFillingTime)) &&
        (this.imageUrl == null ? userVariable.imageUrl == null : this.imageUrl.equals(userVariable.imageUrl)) &&
        (this.ionIcon == null ? userVariable.ionIcon == null : this.ionIcon.equals(userVariable.ionIcon));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.parentId == null ? 0: this.parentId.hashCode());
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.clientId == null ? 0: this.clientId.hashCode());
    result = 31 * result + (this.variableId == null ? 0: this.variableId.hashCode());
    result = 31 * result + (this.defaultUnitId == null ? 0: this.defaultUnitId.hashCode());
    result = 31 * result + (this.minimumAllowedValue == null ? 0: this.minimumAllowedValue.hashCode());
    result = 31 * result + (this.maximumAllowedValue == null ? 0: this.maximumAllowedValue.hashCode());
    result = 31 * result + (this.fillingValue == null ? 0: this.fillingValue.hashCode());
    result = 31 * result + (this.joinWith == null ? 0: this.joinWith.hashCode());
    result = 31 * result + (this.onsetDelay == null ? 0: this.onsetDelay.hashCode());
    result = 31 * result + (this.durationOfAction == null ? 0: this.durationOfAction.hashCode());
    result = 31 * result + (this.variableCategoryId == null ? 0: this.variableCategoryId.hashCode());
    result = 31 * result + (this.updated == null ? 0: this.updated.hashCode());
    result = 31 * result + (this._public == null ? 0: this._public.hashCode());
    result = 31 * result + (this.causeOnly == null ? 0: this.causeOnly.hashCode());
    result = 31 * result + (this.fillingType == null ? 0: this.fillingType.hashCode());
    result = 31 * result + (this.numberOfMeasurements == null ? 0: this.numberOfMeasurements.hashCode());
    result = 31 * result + (this.numberOfProcessedDailyMeasurements == null ? 0: this.numberOfProcessedDailyMeasurements.hashCode());
    result = 31 * result + (this.measurementsAtLastAnalysis == null ? 0: this.measurementsAtLastAnalysis.hashCode());
    result = 31 * result + (this.lastUnitId == null ? 0: this.lastUnitId.hashCode());
    result = 31 * result + (this.lastOriginalUnitId == null ? 0: this.lastOriginalUnitId.hashCode());
    result = 31 * result + (this.lastValue == null ? 0: this.lastValue.hashCode());
    result = 31 * result + (this.lastOriginalValue == null ? 0: this.lastOriginalValue.hashCode());
    result = 31 * result + (this.numberOfCorrelations == null ? 0: this.numberOfCorrelations.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.errorMessage == null ? 0: this.errorMessage.hashCode());
    result = 31 * result + (this.lastSuccessfulUpdateTime == null ? 0: this.lastSuccessfulUpdateTime.hashCode());
    result = 31 * result + (this.standardDeviation == null ? 0: this.standardDeviation.hashCode());
    result = 31 * result + (this.variance == null ? 0: this.variance.hashCode());
    result = 31 * result + (this.minimumRecordedValue == null ? 0: this.minimumRecordedValue.hashCode());
    result = 31 * result + (this.maximumRecordedDailyValue == null ? 0: this.maximumRecordedDailyValue.hashCode());
    result = 31 * result + (this.mean == null ? 0: this.mean.hashCode());
    result = 31 * result + (this.median == null ? 0: this.median.hashCode());
    result = 31 * result + (this.mostCommonUnitId == null ? 0: this.mostCommonUnitId.hashCode());
    result = 31 * result + (this.mostCommonValue == null ? 0: this.mostCommonValue.hashCode());
    result = 31 * result + (this.numberOfUniqueDailyValues == null ? 0: this.numberOfUniqueDailyValues.hashCode());
    result = 31 * result + (this.numberOfChanges == null ? 0: this.numberOfChanges.hashCode());
    result = 31 * result + (this.skewness == null ? 0: this.skewness.hashCode());
    result = 31 * result + (this.kurtosis == null ? 0: this.kurtosis.hashCode());
    result = 31 * result + (this.latitude == null ? 0: this.latitude.hashCode());
    result = 31 * result + (this.longitude == null ? 0: this.longitude.hashCode());
    result = 31 * result + (this.location == null ? 0: this.location.hashCode());
    result = 31 * result + (this.experimentStartTime == null ? 0: this.experimentStartTime.hashCode());
    result = 31 * result + (this.experimentEndTime == null ? 0: this.experimentEndTime.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.updatedAt == null ? 0: this.updatedAt.hashCode());
    result = 31 * result + (this.outcome == null ? 0: this.outcome.hashCode());
    result = 31 * result + (this.sources == null ? 0: this.sources.hashCode());
    result = 31 * result + (this.earliestSourceTime == null ? 0: this.earliestSourceTime.hashCode());
    result = 31 * result + (this.latestSourceTime == null ? 0: this.latestSourceTime.hashCode());
    result = 31 * result + (this.earliestMeasurementTime == null ? 0: this.earliestMeasurementTime.hashCode());
    result = 31 * result + (this.latestMeasurementTime == null ? 0: this.latestMeasurementTime.hashCode());
    result = 31 * result + (this.earliestFillingTime == null ? 0: this.earliestFillingTime.hashCode());
    result = 31 * result + (this.latestFillingTime == null ? 0: this.latestFillingTime.hashCode());
    result = 31 * result + (this.imageUrl == null ? 0: this.imageUrl.hashCode());
    result = 31 * result + (this.ionIcon == null ? 0: this.ionIcon.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserVariable {\n");
    
    sb.append("  parentId: ").append(parentId).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  clientId: ").append(clientId).append("\n");
    sb.append("  variableId: ").append(variableId).append("\n");
    sb.append("  defaultUnitId: ").append(defaultUnitId).append("\n");
    sb.append("  minimumAllowedValue: ").append(minimumAllowedValue).append("\n");
    sb.append("  maximumAllowedValue: ").append(maximumAllowedValue).append("\n");
    sb.append("  fillingValue: ").append(fillingValue).append("\n");
    sb.append("  joinWith: ").append(joinWith).append("\n");
    sb.append("  onsetDelay: ").append(onsetDelay).append("\n");
    sb.append("  durationOfAction: ").append(durationOfAction).append("\n");
    sb.append("  variableCategoryId: ").append(variableCategoryId).append("\n");
    sb.append("  updated: ").append(updated).append("\n");
    sb.append("  _public: ").append(_public).append("\n");
    sb.append("  causeOnly: ").append(causeOnly).append("\n");
    sb.append("  fillingType: ").append(fillingType).append("\n");
    sb.append("  numberOfMeasurements: ").append(numberOfMeasurements).append("\n");
    sb.append("  numberOfProcessedDailyMeasurements: ").append(numberOfProcessedDailyMeasurements).append("\n");
    sb.append("  measurementsAtLastAnalysis: ").append(measurementsAtLastAnalysis).append("\n");
    sb.append("  lastUnitId: ").append(lastUnitId).append("\n");
    sb.append("  lastOriginalUnitId: ").append(lastOriginalUnitId).append("\n");
    sb.append("  lastValue: ").append(lastValue).append("\n");
    sb.append("  lastOriginalValue: ").append(lastOriginalValue).append("\n");
    sb.append("  numberOfCorrelations: ").append(numberOfCorrelations).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  errorMessage: ").append(errorMessage).append("\n");
    sb.append("  lastSuccessfulUpdateTime: ").append(lastSuccessfulUpdateTime).append("\n");
    sb.append("  standardDeviation: ").append(standardDeviation).append("\n");
    sb.append("  variance: ").append(variance).append("\n");
    sb.append("  minimumRecordedValue: ").append(minimumRecordedValue).append("\n");
    sb.append("  maximumRecordedDailyValue: ").append(maximumRecordedDailyValue).append("\n");
    sb.append("  mean: ").append(mean).append("\n");
    sb.append("  median: ").append(median).append("\n");
    sb.append("  mostCommonUnitId: ").append(mostCommonUnitId).append("\n");
    sb.append("  mostCommonValue: ").append(mostCommonValue).append("\n");
    sb.append("  numberOfUniqueDailyValues: ").append(numberOfUniqueDailyValues).append("\n");
    sb.append("  numberOfChanges: ").append(numberOfChanges).append("\n");
    sb.append("  skewness: ").append(skewness).append("\n");
    sb.append("  kurtosis: ").append(kurtosis).append("\n");
    sb.append("  latitude: ").append(latitude).append("\n");
    sb.append("  longitude: ").append(longitude).append("\n");
    sb.append("  location: ").append(location).append("\n");
    sb.append("  experimentStartTime: ").append(experimentStartTime).append("\n");
    sb.append("  experimentEndTime: ").append(experimentEndTime).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  updatedAt: ").append(updatedAt).append("\n");
    sb.append("  outcome: ").append(outcome).append("\n");
    sb.append("  sources: ").append(sources).append("\n");
    sb.append("  earliestSourceTime: ").append(earliestSourceTime).append("\n");
    sb.append("  latestSourceTime: ").append(latestSourceTime).append("\n");
    sb.append("  earliestMeasurementTime: ").append(earliestMeasurementTime).append("\n");
    sb.append("  latestMeasurementTime: ").append(latestMeasurementTime).append("\n");
    sb.append("  earliestFillingTime: ").append(earliestFillingTime).append("\n");
    sb.append("  latestFillingTime: ").append(latestFillingTime).append("\n");
    sb.append("  imageUrl: ").append(imageUrl).append("\n");
    sb.append("  ionIcon: ").append(ionIcon).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
