/**
 * QuantiModo
 * QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class User {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("wpId")
  private Integer wpId = null;
  @SerializedName("displayName")
  private String displayName = null;
  @SerializedName("loginName")
  private String loginName = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("token")
  private String token = null;
  @SerializedName("administrator")
  private Boolean administrator = null;

  /**
   * User id
   **/
  @ApiModelProperty(required = true, value = "User id")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * Wordpress user id
   **/
  @ApiModelProperty(required = true, value = "Wordpress user id")
  public Integer getWpId() {
    return wpId;
  }
  public void setWpId(Integer wpId) {
    this.wpId = wpId;
  }

  /**
   * User display name
   **/
  @ApiModelProperty(required = true, value = "User display name")
  public String getDisplayName() {
    return displayName;
  }
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  /**
   * User login name
   **/
  @ApiModelProperty(required = true, value = "User login name")
  public String getLoginName() {
    return loginName;
  }
  public void setLoginName(String loginName) {
    this.loginName = loginName;
  }

  /**
   * User email
   **/
  @ApiModelProperty(required = true, value = "User email")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * User token
   **/
  @ApiModelProperty(required = true, value = "User token")
  public String getToken() {
    return token;
  }
  public void setToken(String token) {
    this.token = token;
  }

  /**
   * Is user administrator
   **/
  @ApiModelProperty(required = true, value = "Is user administrator")
  public Boolean getAdministrator() {
    return administrator;
  }
  public void setAdministrator(Boolean administrator) {
    this.administrator = administrator;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return (this.id == null ? user.id == null : this.id.equals(user.id)) &&
        (this.wpId == null ? user.wpId == null : this.wpId.equals(user.wpId)) &&
        (this.displayName == null ? user.displayName == null : this.displayName.equals(user.displayName)) &&
        (this.loginName == null ? user.loginName == null : this.loginName.equals(user.loginName)) &&
        (this.email == null ? user.email == null : this.email.equals(user.email)) &&
        (this.token == null ? user.token == null : this.token.equals(user.token)) &&
        (this.administrator == null ? user.administrator == null : this.administrator.equals(user.administrator));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.wpId == null ? 0: this.wpId.hashCode());
    result = 31 * result + (this.displayName == null ? 0: this.displayName.hashCode());
    result = 31 * result + (this.loginName == null ? 0: this.loginName.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.token == null ? 0: this.token.hashCode());
    result = 31 * result + (this.administrator == null ? 0: this.administrator.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  wpId: ").append(wpId).append("\n");
    sb.append("  displayName: ").append(displayName).append("\n");
    sb.append("  loginName: ").append(loginName).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  token: ").append(token).append("\n");
    sb.append("  administrator: ").append(administrator).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
